###
POST http://localhost:3000/user/register
Content-Type: application/json


{
  "username": "hang",
  "password": "123456"
}


### 
GET http://localhost:3000/user/redirect 

###
POST http://localhost:3000/app/create-cat
Content-Type: application/json

{
  "name": "hang",
  "age": 18
}
